# Generated by Django 2.2.5 on 2019-10-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191025_0708'),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='company',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Town'),
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Ocupada'), ('2', 'Mantenimiento')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('status', models.CharField(blank=True, choices=[('1', 'Reserved'), ('2', 'Available')], default='A', max_length=1)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='sport.Company')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Schedule'),
        ),
    ]
